spring:
  application:
    name: fashion_web_be
  datasource:
    url: jdbc:postgresql://localhost:5432/pbl6
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  main:
    allow-bean-definition-overriding: true
  jwt:
    signerKey: 8puVMNg/6a1Lnb2ZhuqtwdcVaRW5tqZND6J4Y9vQ+/jG5kKMwVVtPGNKXgai/dxN
    expiration: 3600
    refreshable-duration: 36000
    issuer: auth-service
  redis:
    porrt: 6379

  data:
    redis:
      host: localhost
      timeout: 2000
  cache:
    type: redis

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

server:
  port: 8080
  servlet:
    context-path: /api


